package com.letsteamup.api.letsteamupapi.model;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Class representation of Projects
 */
public class Project
{

    @JsonProperty int id; //Generated by DAO

    // -- Defined by user -- //
    @JsonProperty String title;
    @JsonProperty String description;
    @JsonProperty String elevatorPitch;
    @JsonProperty String skillsNeeded;

    // -- Defined on creation -- //
    @JsonProperty User owner;

    // -- Defined through updates -- //
    @JsonProperty List<User> team;

    public Project(@JsonProperty int id, @JsonProperty String title, @JsonProperty String description, @JsonProperty String elevatorPitch,
                    @JsonProperty User owner, @JsonProperty String skillsNeeded)
    {
        this.id = id;
        this.title = title;
        this.description = description;
        this.elevatorPitch = elevatorPitch;
        this.owner = owner;
        this.skillsNeeded = skillsNeeded;
    }

    public Project()
    {
        
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getElevatorPitch() {
        return elevatorPitch;
    }

    public void setElevatorPitch(String elevatorPitch) {
        this.elevatorPitch = elevatorPitch;
    }

    public String getSkillsNeeded() {
        return skillsNeeded;
    }

    public void setSkillsNeeded(String skillsNeeded) {
        this.skillsNeeded = skillsNeeded;
    }

    public User getOwner() {
        return owner;
    }

    public void setOwner(User owner) {
        this.owner = owner;
    }

    public List<User> getTeam() {
        return team;
    }

    public void setTeam(List<User> team) {
        this.team = team;
    }
}